// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: exchange/price.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Coin           string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Price          float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	EventTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_exchange_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_exchange_price_proto_rawDescGZIP(), []int{0}
}

func (x *PriceUpdate) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *PriceUpdate) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceUpdate) GetEventTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamp
	}
	return nil
}

var File_exchange_price_proto protoreflect.FileDescriptor

const file_exchange_price_proto_rawDesc = "" +
	"\n" +
	"\x14exchange/price.proto\x12\acoincap\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\vPriceUpdate\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12C\n" +
	"\x0fevent_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eeventTimestampB\x18Z\x16./compiled-go/exchangeb\x06proto3"

var (
	file_exchange_price_proto_rawDescOnce sync.Once
	file_exchange_price_proto_rawDescData []byte
)

func file_exchange_price_proto_rawDescGZIP() []byte {
	file_exchange_price_proto_rawDescOnce.Do(func() {
		file_exchange_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_price_proto_rawDesc), len(file_exchange_price_proto_rawDesc)))
	})
	return file_exchange_price_proto_rawDescData
}

var file_exchange_price_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exchange_price_proto_goTypes = []any{
	(*PriceUpdate)(nil),           // 0: coincap.PriceUpdate
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_exchange_price_proto_depIdxs = []int32{
	1, // 0: coincap.PriceUpdate.event_timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_exchange_price_proto_init() }
func file_exchange_price_proto_init() {
	if File_exchange_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_price_proto_rawDesc), len(file_exchange_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exchange_price_proto_goTypes,
		DependencyIndexes: file_exchange_price_proto_depIdxs,
		MessageInfos:      file_exchange_price_proto_msgTypes,
	}.Build()
	File_exchange_price_proto = out.File
	file_exchange_price_proto_goTypes = nil
	file_exchange_price_proto_depIdxs = nil
}
